### ISSUE TITLE
Update bookmark after changing visibility of selection

### ISSUE THREAD

**Issue by BeFresh78** [MicrosoftDocs/powerbi-docs.nl-nl#6]
Please note: When using the selection pane in combination with bookmarks, make sure you right-click on the corresponding bookmark an click "update" after changing the visibility of a selection. Otherwise visibility will revert to default.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Bladwijzers in Power BI Desktop gebruiken om inzichten te delen en verhalen te vertellen - Power BI](https://docs.microsoft.com/nl-nl/power-bi/desktop-bookmarks#feedback)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @BeFresh78
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @BeFresh78, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/1931. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
